import { expect, test, screenshotPath } from "./fixtures";

test("previews font choices and color effects, cancels, then persists them across themes and reload", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Desktop settings scope");
  const savedAppearance = await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance);
  const name = page.locator(".site-card .site-name").first();
  const originalFont = await name.evaluate(element => getComputedStyle(element).fontFamily);
  await page.getByRole("button", { name: "打开设置" }).click();
  const panel = page.getByRole("dialog", { name: "设置", exact: true });
  await expect(panel.getByRole("group", { name: "文字大小" })).toHaveCount(0);
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("button", { name: "宋体 / 衬线" }).click();
  await panel.getByRole("slider", { name: "整体字号", exact: true }).fill("115");
  await panel.getByRole("group", { name: "文字配色", exact: true }).getByRole("button", { name: "自定义", exact: true }).click();
  await panel.getByRole("button", { name: "白色文字" }).click();
  await panel.getByRole("button", { name: "描边", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(255, 255, 255)");
  await expect(name).toHaveCSS("font-family", /SimSun/);
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await expect(panel.getByRole("heading", { name: "字体", exact: true })).toHaveCSS("color", "rgb(23, 28, 38)");
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance)).toEqual(savedAppearance);
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(name).toHaveCSS("font-family", originalFont);
  await expect(name).toHaveCSS("color", "rgb(23, 28, 38)");

  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("button", { name: "本机字体", exact: true }).click();
  await panel.getByRole("textbox", { name: "本机字体名称" }).fill("Consolas");
  await panel.getByRole("group", { name: "文字配色", exact: true }).getByRole("button", { name: "自定义", exact: true }).click();
  await panel.getByRole("button", { name: "自定义主要文字颜色" }).click();
  const picker = panel.getByRole("dialog", { name: "选择自定义颜色" });
  await picker.getByRole("textbox", { name: "十六进制颜色" }).fill("4b277c");
  await picker.getByRole("textbox", { name: "十六进制颜色" }).press("Enter");
  await panel.getByRole("button", { name: "自定义主要文字颜色" }).click();
  await panel.getByRole("button", { name: "柔光", exact: true }).click();
  await panel.getByRole("slider", { name: "效果强度" }).fill("75");
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await panel.getByRole("slider", { name: "效果强度" }).fill("0");
  await expect(name).toHaveCSS("text-shadow", "none");
  await panel.getByRole("slider", { name: "效果强度" }).fill("75");
  await page.screenshot({ path: screenshotPath("typography-custom-desktop.png"), animations: "disabled" });
  await panel.getByRole("button", { name: "保存设置" }).click();
  await page.reload();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  await expect(name).toHaveCSS("font-family", /Consolas/);
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("button", { name: "深色", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await expect(panel.getByRole("heading", { name: "字体", exact: true })).toHaveCSS("color", "rgb(232, 236, 243)");
  await panel.getByRole("button", { name: "恢复默认字体" }).click();
  await expect(name).toHaveCSS("color", "rgb(232, 236, 243)");
  await expect(name).toHaveCSS("font-family", originalFont);
  await expect(name).toHaveCSS("text-shadow", "none");
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
});

test("switches native display-text selection without blocking input selection or editing", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Desktop settings scope");
  const title = page.locator(".collection-heading h2");
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).not.toBe("");
  await page.getByRole("button", { name: "打开设置" }).click();
  const panel = page.getByRole("dialog", { name: "设置", exact: true });
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).uncheck();
  await expect(title).toHaveCSS("user-select", "none");
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(title).not.toHaveCSS("user-select", "none");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).uncheck();
  await panel.getByRole("button", { name: "保存设置" }).click();
  await page.reload();
  await expect(title).toHaveCSS("user-select", "none");
  await page.evaluate(() => window.getSelection()?.removeAllRanges());
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).toBe("");
  const search = page.locator(".search-input input");
  await search.fill("可选择编辑");
  await search.press("Control+a");
  expect(await search.evaluate((input: HTMLInputElement) => input.selectionEnd! - input.selectionStart!)).toBe(5);
  await search.press("Backspace");
  await expect(search).toHaveValue("");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).check();
  await panel.getByRole("button", { name: "保存设置" }).click();
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).not.toBe("");
});
