import { expect, test, screenshotPath } from "./fixtures";
import { resolve } from "node:path";

test("previews font choices and color effects, cancels, then persists them across themes and reload", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Desktop settings scope");
  const savedAppearance = await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance);
  const name = page.locator(".site-card .site-name").first();
  const originalFont = await name.evaluate(element => getComputedStyle(element).fontFamily);
  await page.getByRole("button", { name: "打开设置" }).click();
  const panel = page.getByRole("dialog", { name: "设置", exact: true });
  await expect(panel.getByRole("group", { name: "文字大小" })).toHaveCount(0);
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("button", { name: "宋体 / 衬线" }).click();
  await panel.getByRole("slider", { name: "整体字号", exact: true }).fill("115");
  await panel.locator("summary").filter({ hasText: "文字颜色" }).click();
  await panel.getByRole("checkbox", { name: "主题关联字体颜色" }).uncheck();
  await panel.getByRole("button", { name: "白色文字" }).click();
  await panel.locator("summary").filter({ hasText: "文字增强" }).click();
  await panel.getByRole("button", { name: "柔光", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(255, 255, 255)");
  await expect(name).toHaveCSS("font-family", /SimSun/);
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await expect(panel.getByRole("heading", { name: "字体", exact: true })).toHaveCSS("color", "rgb(255, 255, 255)");
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance)).toEqual(savedAppearance);
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(name).toHaveCSS("font-family", originalFont);
  await expect(name).toHaveCSS("color", "rgb(23, 28, 38)");

  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("button", { name: "本地字体", exact: true }).click();
  await expect(panel.getByRole("button", { name: "选择已安装字体" })).toBeVisible();
  await panel.getByLabel("字体文件", { exact: true }).setInputFiles(resolve("public/fonts/LXGWWenKai-Regular.woff2"));
  await expect(panel.getByText("当前字体：LXGWWenKai-Regular", { exact: true })).toBeVisible();
  await expect(panel.getByRole("checkbox", { name: "主题关联字体颜色" })).toBeVisible();
  await panel.getByRole("checkbox", { name: "主题关联字体颜色" }).uncheck();
  await panel.getByRole("button", { name: "自定义主要文字颜色" }).click();
  const picker = panel.getByRole("dialog", { name: "选择自定义颜色" });
  await picker.getByRole("textbox", { name: "十六进制颜色" }).fill("4b277c");
  await picker.getByRole("textbox", { name: "十六进制颜色" }).press("Enter");
  await panel.getByRole("button", { name: "自定义主要文字颜色" }).click();
  await expect(panel.getByRole("button", { name: "柔光", exact: true })).toBeVisible();
  await panel.getByRole("button", { name: "柔光", exact: true }).click();
  await panel.locator("summary").filter({ hasText: "效果微调" }).click();
  await panel.getByRole("slider", { name: "效果强度" }).fill("75");
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await panel.getByRole("slider", { name: "效果强度" }).fill("0");
  await expect(name).toHaveCSS("text-shadow", "none");
  await panel.getByRole("slider", { name: "效果强度" }).fill("75");
  await page.screenshot({ path: screenshotPath("typography-custom-desktop.png"), animations: "disabled" });
  await panel.getByRole("button", { name: "保存设置" }).click();
  await page.reload();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  const assetId = await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance.customFontAssetId as string);
  expect(assetId).toMatch(/^font-/);
  const family = `Mysimple_Local_${assetId}`;
  await expect(name).toHaveCSS("font-family", new RegExp(family));
  await expect.poll(() => page.evaluate(family => [...document.fonts].some(face => face.family.replaceAll('"', "") === family && face.status === "loaded"), family)).toBe(true);
  await expect(name).not.toHaveCSS("text-shadow", "none");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("button", { name: "深色", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await expect(panel.getByRole("heading", { name: "字体", exact: true })).toHaveCSS("color", "rgb(75, 39, 124)");
  await panel.getByRole("button", { name: "恢复默认字体" }).click();
  await expect(name).toHaveCSS("color", "rgb(232, 236, 243)");
  await expect(name).toHaveCSS("font-family", originalFont);
  await expect(name).toHaveCSS("text-shadow", "none");
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(name).toHaveCSS("color", "rgb(75, 39, 124)");
});

test("offers six fonts, direct overall size and collapsed section sizes across the full 70–130 percent range", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Desktop settings scope");
  for (const size of [70, 130]) {
    await page.getByRole("button", { name: "打开设置" }).click();
    const panel = page.getByRole("dialog", { name: "设置", exact: true });
    await panel.getByRole("tab", { name: "字体调节" }).click();
    await expect(panel.getByRole("slider")).toHaveCount(1);
    await expect(panel.getByRole("checkbox", { name: "主题关联字体颜色" })).toHaveCount(0);
    await expect(panel.getByRole("group", { name: "文字效果", exact: true })).toHaveCount(0);
    const fontButtons = panel.getByRole("group", { name: "字体选择" }).getByRole("button");
    await expect(fontButtons).toHaveCount(6);
    const positions = await fontButtons.evaluateAll(buttons => buttons.map(button => ({
      x: button.getBoundingClientRect().x, y: button.getBoundingClientRect().y,
    })));
    expect(new Set(positions.map(item => item.x)).size).toBe(3);
    expect(new Set(positions.map(item => item.y)).size).toBe(2);
    await panel.getByRole("button", { name: "霞鹜文楷", exact: true }).click();
    const loaded = await page.evaluate(async () => {
      const faces = await document.fonts.load('16px "LXGW WenKai"', "中文收藏");
      return faces.length > 0 && faces.every(face => face.status === "loaded");
    });
    expect(loaded).toBe(true);
    const slider = panel.getByRole("slider", { name: "整体字号", exact: true });
    await expect(slider).toBeVisible();
    await expect(slider).toHaveAttribute("min", "70");
    await expect(slider).toHaveAttribute("max", "130");
    await slider.fill(String(size));
    const sections = panel.locator("summary").filter({ hasText: "分区字号" });
    await sections.click();
    await expect(panel.getByRole("slider")).toHaveCount(4);
    await sections.click();
    await expect(panel.getByRole("slider")).toHaveCount(1);
    await expect(slider).toHaveValue(String(size));
    await panel.getByRole("button", { name: "保存设置" }).click();
    await page.reload();
    await expect(page.locator(".site-card .site-name").first()).toHaveCSS("font-family", /LXGW WenKai/);
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("site-hub:v1")!).appearance);
    expect(saved).toMatchObject({ fontFamily: "wenkai", fontScale: size });
  }
});

test("switches native display-text selection without blocking input selection or editing", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Desktop settings scope");
  const title = page.locator(".collection-heading h2");
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).not.toBe("");
  await page.getByRole("button", { name: "打开设置" }).click();
  const panel = page.getByRole("dialog", { name: "设置", exact: true });
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).uncheck();
  await expect(title).toHaveCSS("user-select", "none");
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await expect(title).not.toHaveCSS("user-select", "none");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).uncheck();
  await panel.getByRole("button", { name: "保存设置" }).click();
  await page.reload();
  await expect(title).toHaveCSS("user-select", "none");
  await page.evaluate(() => window.getSelection()?.removeAllRanges());
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).toBe("");
  const search = page.locator(".search-input input");
  await search.fill("可选择编辑");
  await search.press("Control+a");
  expect(await search.evaluate((input: HTMLInputElement) => input.selectionEnd! - input.selectionStart!)).toBe(5);
  await search.press("Backspace");
  await expect(search).toHaveValue("");
  await page.getByRole("button", { name: "打开设置" }).click();
  await panel.getByRole("tab", { name: "字体调节" }).click();
  await panel.getByRole("checkbox", { name: "允许选择展示文字" }).check();
  await panel.getByRole("button", { name: "保存设置" }).click();
  await title.dblclick();
  expect(await page.evaluate(() => window.getSelection()?.toString())).not.toBe("");
});
