import type { ComponentType } from "react";
import {
  BookOpen,
  BookmarkSimple,
  Brain,
  Briefcase,
  CalendarBlank,
  ChartBar,
  ChartLineUp,
  ChatCircleDots,
  Cloud,
  Camera,
  Atom,
  CurrencyCny,
  Code,
  Database,
  FilmStrip,
  Flask,
  Folder,
  GameController,
  GlobeHemisphereWest,
  GraduationCap,
  Headphones,
  Heart,
  House,
  Image,
  Kanban,
  Lightning,
  Lightbulb,
  ListChecks,
  MapPin,
  Microphone,
  MagnifyingGlass,
  MusicNotes,
  Newspaper,
  Package,
  PaintBrush,
  Palette,
  PenNib,
  Play,
  Robot,
  RocketLaunch,
  ShieldCheck,
  ShoppingBag,
  Star,
  Stack,
  TerminalWindow,
  TestTube,
  UserCircle,
  Wrench,
  type IconProps,
} from "@phosphor-icons/react";
import type { CategoryIcon as CategoryIconName } from "../types";

const icons: Record<CategoryIconName, ComponentType<IconProps>> = {
  "magnifying-glass": MagnifyingGlass,
  code: Code,
  "pen-nib": PenNib,
  play: Play,
  "book-open": BookOpen,
  briefcase: Briefcase,
  wrench: Wrench,
  folder: Folder,
  database: Database,
  terminal: TerminalWindow,
  cloud: Cloud,
  chat: ChatCircleDots,
  shopping: ShoppingBag,
  game: GameController,
  music: MusicNotes,
  image: Image,
  calendar: CalendarBlank,
  chart: ChartBar,
  robot: Robot,
  bookmark: BookmarkSimple,
  globe: GlobeHemisphereWest,
  lightning: Lightning,
  heart: Heart,
  star: Star,
  house: House,
  lightbulb: Lightbulb,
  palette: Palette,
  "paint-brush": PaintBrush,
  camera: Camera,
  "film-strip": FilmStrip,
  headphones: Headphones,
  newspaper: Newspaper,
  "graduation-cap": GraduationCap,
  brain: Brain,
  atom: Atom,
  "test-tube": TestTube,
  "rocket-launch": RocketLaunch,
  kanban: Kanban,
  "list-checks": ListChecks,
  "chart-line-up": ChartLineUp,
  stack: Stack,
  "map-pin": MapPin,
  "currency-cny": CurrencyCny,
  "shield-check": ShieldCheck,
  "user-circle": UserCircle,
  microphone: Microphone,
  package: Package,
  flask: Flask,
};

interface CategoryIconProps extends IconProps {
  name: CategoryIconName;
}

export function CategoryIcon({ name, ...props }: CategoryIconProps) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" weight="regular" {...props} />;
}
